### PR TITLE
Update all deps

### PR DESCRIPTION
**Pull request by WhiteOlivierus**
Please could this be fixed? At the moment when installing this package I have to do force, which comes with it's own challanges

### CODE REVIEW

**Comment by Shinigami92** [comment]
I have set Renovate for the dependency updates and might have a look when I will find the time, but this could be next week, because I'm very busy right now.

Beside that, you should not be affected by devDependencies except you are a contributor to the repo.

All other versions like peerDependencies are set in a wide-range (using `~` or `^`), so there should also not be a conflict 🤔 

I also do not understand what you mean by "need of using force". Which force do you mean?

As this PR also includes wrong files like `package-lock.json` files, but it driven by pnpm, I will close this PR as invalid and will stick to Renovate when I find the time.

**Comment by WhiteOlivierus** [comment]
@Shinigami92 What I meant is that I have to use `npm i --force` to install this package, which I love btw.

**Comment by Shinigami92** [comment]
> @Shinigami92 What I meant is that I have to use `npm i --force` to install this package, which I love btw.

> The -f or --force argument will force npm to fetch remote resources even if a local copy exists on disk.
https://docs.npmjs.com/cli/v10/commands/npm-install

This should have nothing todo with the dependencies of this repo/package.

**Comment by WhiteOlivierus** [comment]
```
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: vite-plugin-ts-nameof@3.0.0
npm error Found: @typescript-nameof/types@0.0.10
npm error node_modules/@typescript-nameof/types
npm error   dev @typescript-nameof/types@"^0.0.10" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @typescript-nameof/types@"^0.0.7" from vite-plugin-ts-nameof@3.0.0
npm error node_modules/vite-plugin-ts-nameof
npm error   dev vite-plugin-ts-nameof@"^3.0.0" from the root project
npm error
npm error Conflicting peer dependency: @typescript-nameof/types@0.0.7
npm error node_modules/@typescript-nameof/types
npm error   peer @typescript-nameof/types@"^0.0.7" from vite-plugin-ts-nameof@3.0.0
npm error   node_modules/vite-plugin-ts-nameof
npm error     dev vite-plugin-ts-nameof@"^3.0.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error C:\Users\dijkstrab\AppData\Local\npm-cache\_logs\2024-07-31T08_54_13_369Z-eresolve-report.txt
npm error A complete log of this run can be found in: C:\Users\dijkstrab\AppData\Local\npm-cache\_logs\2024-07-31T08_54_13_369Z-debug-0.log
```

I do get dependency errors when installing it normally

**Comment by Shinigami92** [comment]
@WhiteOlivierus What happens if you remove your `node_modules` and `package-lock.json` and then run `npm install`?

**Comment by WhiteOlivierus** [comment]
Gives the same error, cache has been emptied too

**Comment by Shinigami92** [comment]
> Gives the same error, cache has been emptied too

Okay, that is absolutely weird
Or in other words, seems like there is something I do not understand regarding semver
The only assumption I currently have, is that is has something to do with 0.x.x versions in semver

**Comment by WhiteOlivierus** [comment]
Maybe a good question, do you see the same behaviour as us here. Because maybe there is something going on in our system over here. In a new Vite react project

**Comment by WhiteOlivierus** [comment]
Figured it out:

`"@typescript-nameof/types": "^0.0.7",`

was

`"@typescript-nameof/types": "^0.0.10",`

This might have been user error. Sorry for the hassle

**Pull request closed without merging**
